// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRY1cyKoXxsUeOEt8xCaRZnCwz3cJ_iPM',
    appId: '1:926683612182:web:3f6b3e566fcff6af716137',
    messagingSenderId: '926683612182',
    projectId: 'quickensolcrm',
    authDomain: 'quickensolcrm.firebaseapp.com',
    storageBucket: 'quickensolcrm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglBX7-MvYEJDBdCvX0kwqwxeWd_rCdwo',
    appId: '1:926683612182:android:d552cc1618ee17ca716137',
    messagingSenderId: '926683612182',
    projectId: 'quickensolcrm',
    storageBucket: 'quickensolcrm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchkgOq-DT6dT452E95YZO2LKGJnrbQ_A',
    appId: '1:926683612182:ios:06d396a60d1b83ad716137',
    messagingSenderId: '926683612182',
    projectId: 'quickensolcrm',
    storageBucket: 'quickensolcrm.appspot.com',
    iosBundleId: 'com.quick.quickensolcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchkgOq-DT6dT452E95YZO2LKGJnrbQ_A',
    appId: '1:926683612182:ios:06d396a60d1b83ad716137',
    messagingSenderId: '926683612182',
    projectId: 'quickensolcrm',
    storageBucket: 'quickensolcrm.appspot.com',
    iosBundleId: 'com.quick.quickensolcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRY1cyKoXxsUeOEt8xCaRZnCwz3cJ_iPM',
    appId: '1:926683612182:web:84313c8cc53f7869716137',
    messagingSenderId: '926683612182',
    projectId: 'quickensolcrm',
    authDomain: 'quickensolcrm.firebaseapp.com',
    storageBucket: 'quickensolcrm.appspot.com',
  );
}
